### ISSUE TITLE
Split bar always transparent

### ISSUE THREAD

**Issue by marawangamal** [gfazioli/mantine-split-pane#6]
I am using the latest release 0.3.5 and the split bar is always transparent. However, on hover it has the specified colour.

**Comment by gfazioli** [comment]
@marawangamal you mean
<img width="449" alt="image" src="https://github.com/user-attachments/assets/a05251bd-349f-4911-acf4-016c16ce3326">

**Comment by gfazioli** [comment]
@marawangamal which browser are you using?
<img width="985" alt="image" src="https://github.com/user-attachments/assets/78f6c9e5-64a9-4158-9836-5b50b1e6f672">

**Comment by marawangamal** [comment]
Yes. It sometimes happens not always. 

I had this import in my main entry point (App.tsx)
import '@gfazioli/mantine-split-pane/styles.css';

and this import my layout component (LayoutSplit.tsx)
import '@gfazioli/mantine-split-pane/styles.layer.css';

I think removing import '@gfazioli/mantine-split-pane/styles.layer.css'; fixes it

**Comment by gfazioli** [comment]
@marawangamal you can find more about `layer` here https://mantine.dev/styles/mantine-styles/#css-layers
but I don't think you need to use that. It's only for edge cases

let me know if we can close this issue
